#! /bin/sh
bspc config border_width        	0
bspc config window_gap   			0

bspc config top_padding       		15
bspc config left_padding       		0
bspc config right_padding       	0
bspc config bottom_padding       	0

bspc config focused_border_color 	\#F0B4C0
bspc config normal_border_color 	\#B7B7BC

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true

bspc monitor -d I II III IV V

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer 	true

