#! /bin/sh
bspc config border_width        	3
bspc config window_gap   			25

bspc config top_padding       		25
bspc config left_padding       		0
bspc config right_padding       	0
bspc config bottom_padding       	0

bspc config focused_border_color 	\#F0B4C0
bspc config normal_border_color 	\#B7B7BC

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true

bspc monitor DP-2 -d I II
bspc monitor DP-0 -d III IV

bspc config focus_follows_pointer 	true

